name: CI

on:
  push:
    brnaches:
      - main
  pull_request:

  jobs:
    build-test:
      runs-on: ubuntu-latest
      steps:
        - name: Clonar el repsoitorio
          uses: actions/checkout@v4

        - name: Configurar Java
          uses: actions/setup-jave@v4
          with:
            distribution: 'temurin'
            jave-version: '17'

        - name: Ejecutar pruebas

          run: ./gradlew test

        - name: Construir
          run: ./gradlw build
